#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'S. Andrew Ning',
 'author_email': 'andrew.ning@nrel.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'Tower Systems Engineering Model for NREL WISDEM',
 'download_url': '',
 'entry_points': '[openmdao.component]\nwisdem.towerse.tower.Wind=wisdem.towerse.tower:Wind\nwisdem.towerse.tower.TowerWindDrag=wisdem.towerse.tower:TowerWindDrag\nwisdem.towerse.tower.LogWind=wisdem.towerse.tower:LogWind\nwisdem.towerse.tower.TowerDiscretization=wisdem.towerse.tower:TowerDiscretization\nwisdem.towerse.tower.TowerWaveDrag=wisdem.towerse.tower:TowerWaveDrag\nwisdem.towerse.tower.Wave=wisdem.towerse.tower:Wave\nwisdem.towerse.tower.Tower=wisdem.towerse.tower:Tower\nwisdem.towerse.tower.Soil=wisdem.towerse.tower:Soil\nwisdem.towerse.tower.PowerWind=wisdem.towerse.tower:PowerWind\nwisdem.towerse.tower.TowerSoil=wisdem.towerse.tower:TowerSoil\nwisdem.towerse.tower.TowerStruc=wisdem.towerse.tower:TowerStruc\nwisdem.towerse.tower.LinearWaves=wisdem.towerse.tower:LinearWaves\n\n[openmdao.container]\nwisdem.towerse.tower.Wind=wisdem.towerse.tower:Wind\nwisdem.towerse.tower.TowerWindDrag=wisdem.towerse.tower:TowerWindDrag\nwisdem.towerse.tower.Tower=wisdem.towerse.tower:Tower\nwisdem.towerse.tower.TowerSoil=wisdem.towerse.tower:TowerSoil\nwisdem.towerse.tower.PowerWind=wisdem.towerse.tower:PowerWind\nwisdem.towerse.tower.Wave=wisdem.towerse.tower:Wave\nwisdem.towerse.tower.Soil=wisdem.towerse.tower:Soil\nwisdem.towerse.tower.LinearWaves=wisdem.towerse.tower:LinearWaves\nwisdem.towerse.tower.AeroLoads=wisdem.towerse.tower:AeroLoads\nwisdem.towerse.tower.TowerStruc=wisdem.towerse.tower:TowerStruc\nwisdem.towerse.tower.TowerDiscretization=wisdem.towerse.tower:TowerDiscretization\nwisdem.towerse.tower.TowerWaveDrag=wisdem.towerse.tower:TowerWaveDrag\nwisdem.towerse.tower.LogWind=wisdem.towerse.tower:LogWind',
 'include_package_data': True,
 'install_requires': ['openmdao.main', 'pBEAM', 'wisdem.commonse'],
 'dependency_links': ['https://github.com/NREL-WISDEM/pBEAM/tarball/master#egg=pBEAM-0.1.0'],
 'keywords': ['openmdao'],
 'license': 'Apache License, Version 2.0',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'towerse',
 'package_data': {'towerse': ['sphinx_build/html/.buildinfo',
                              'sphinx_build/html/genindex.html',
                              'sphinx_build/html/index.html',
                              'sphinx_build/html/objects.inv',
                              'sphinx_build/html/pkgdocs.html',
                              'sphinx_build/html/search.html',
                              'sphinx_build/html/searchindex.js',
                              'sphinx_build/html/srcdocs.html',
                              'sphinx_build/html/usage.html',
                              'sphinx_build/html/_sources/index.txt',
                              'sphinx_build/html/_sources/pkgdocs.txt',
                              'sphinx_build/html/_sources/srcdocs.txt',
                              'sphinx_build/html/_sources/usage.txt',
                              'sphinx_build/html/_static/ajax-loader.gif',
                              'sphinx_build/html/_static/basic.css',
                              'sphinx_build/html/_static/comment-bright.png',
                              'sphinx_build/html/_static/comment-close.png',
                              'sphinx_build/html/_static/comment.png',
                              'sphinx_build/html/_static/default.css',
                              'sphinx_build/html/_static/doctools.js',
                              'sphinx_build/html/_static/down-pressed.png',
                              'sphinx_build/html/_static/down.png',
                              'sphinx_build/html/_static/file.png',
                              'sphinx_build/html/_static/jquery.js',
                              'sphinx_build/html/_static/minus.png',
                              'sphinx_build/html/_static/plus.png',
                              'sphinx_build/html/_static/pygments.css',
                              'sphinx_build/html/_static/searchtools.js',
                              'sphinx_build/html/_static/sidebar.js',
                              'sphinx_build/html/_static/underscore.js',
                              'sphinx_build/html/_static/up-pressed.png',
                              'sphinx_build/html/_static/up.png',
                              'sphinx_build/html/_static/websupport.js']},
 'package_dir': {'': 'src'},
 'packages': ['wisdem', 'wisdem.towerse'],
 'url': '',
 'version': '0.1',
 'zip_safe': False}


setup(**kwargs)

